#!/usr/bin/env bash
# regen-system-prompt.sh — concatenate kernel/01-04.md into a single
# system-prompt.md for Goose to load.
#
# Run after any change to kernel/*.md, or wire into a pre-commit hook.
#
# Usage: ./goose-config/regen-system-prompt.sh

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
KERNEL_DIR="$REPO_ROOT/kernel"
OUTPUT="$REPO_ROOT/goose-config/system-prompt.md"

if [[ ! -d "$KERNEL_DIR" ]]; then
  echo "ERROR: kernel/ directory not found at $KERNEL_DIR" >&2
  exit 1
fi

# Header + concatenation of compact kernel files in numeric order.
cat > "$OUTPUT" <<EOF
# Hypatia — System Prompt
<!-- Generated by goose-config/regen-system-prompt.sh from kernel/01-04.md -->
<!-- Regenerate after any change to kernel/*.md -->
<!-- Last regenerated: $(date -u +"%Y-%m-%dT%H:%M:%SZ") -->

EOF

for file in "$KERNEL_DIR"/0*.md; do
  echo "" >> "$OUTPUT"
  echo "---" >> "$OUTPUT"
  echo "" >> "$OUTPUT"
  cat "$file" >> "$OUTPUT"
done

# Footer pointing Hypatia at MCP resources.
cat >> "$OUTPUT" <<EOF


---

# Loaded MCP resources

Deeper protocol content is served on demand by the hypatia-protocols
MCP server registered in goose-config/config.yaml. See its README for
the full URI inventory.

The compact kernel above carries:
- 01: identity (who Hypatia is, super-objective, irreducible self, non-negotiables)
- 02: voice (register, cadence, prohibitions)
- 03: critical gates (inbox boundary, destructive action tiers, security never-violates)
- 04: routing (request classification, Decision Routes A-F summary, skills-loading discipline)

When a user request matches a protocol keyword, Hypatia instructs Goose
to load the matching MCP resource via the hypatia-protocols extension.
EOF

echo "Regenerated $OUTPUT ($(wc -l < "$OUTPUT") lines, $(wc -w < "$OUTPUT") words)"
