#!/usr/bin/env bash
# regen-system-prompt.sh — concatenate kernel/01-04.md into a single
# system-prompt.md, then embed it as the instructions of the Hypatia
# recipe (goose-config/hypatia-recipe.yaml) — Goose 1.40's custom-distro
# mechanism. Both outputs are generated + gitignored.
#
# Run after any change to kernel/*.md, or wire into a pre-commit hook.
#
# Usage: ./goose-config/regen-system-prompt.sh

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
KERNEL_DIR="$REPO_ROOT/kernel"
OUTPUT="$REPO_ROOT/goose-config/system-prompt.md"

if [[ ! -d "$KERNEL_DIR" ]]; then
  echo "ERROR: kernel/ directory not found at $KERNEL_DIR" >&2
  exit 1
fi

# Header + concatenation of compact kernel files in numeric order.
cat > "$OUTPUT" <<EOF
# Hypatia — System Prompt
<!-- Generated by goose-config/regen-system-prompt.sh from kernel/01-04.md -->
<!-- Regenerate after any change to kernel/*.md -->
<!-- Last regenerated: $(date -u +"%Y-%m-%dT%H:%M:%SZ") -->

EOF

for file in "$KERNEL_DIR"/0*.md; do
  echo "" >> "$OUTPUT"
  echo "---" >> "$OUTPUT"
  echo "" >> "$OUTPUT"
  cat "$file" >> "$OUTPUT"
done

# Footer pointing Hypatia at MCP resources.
cat >> "$OUTPUT" <<EOF


---

# Loaded MCP resources

Deeper protocol content is served on demand by the hypatia-protocols
MCP server registered in goose-config/config.yaml. See its README for
the full URI inventory.

The compact kernel above carries:
- 01: identity (who Hypatia is, super-objective, irreducible self, non-negotiables)
- 02: voice (register, cadence, prohibitions)
- 03: critical gates (inbox boundary, destructive action tiers, security never-violates)
- 04: routing (request classification, Decision Routes A-F summary, skills-loading discipline)

When a user request matches a protocol keyword, Hypatia instructs Goose
to load the matching MCP resource via the hypatia-protocols extension.
EOF

echo "Regenerated $OUTPUT ($(wc -l < "$OUTPUT") lines, $(wc -w < "$OUTPUT") words)"

# ── Hypatia recipe (Goose 1.40 custom-distro vehicle) ──────────────
# The recipe carries: the kernel as `instructions`, the Hypatia-specific
# extension set, and provider/model settings (Q-17). Hypatia-only
# extensions live here, NOT in ~/.config/goose/config.yaml, so AJ's
# other Goose usage keeps its own defaults.
#
# Paths are absolute per Phase 1.5 (Mac-only); recipe env expansion is
# unverified in 1.40. Validate after regen: goose recipe validate <file>.

RECIPE="$REPO_ROOT/goose-config/hypatia-recipe.yaml"
VAULT_PATH="$(sed -n 's/^  path: //p' "$REPO_ROOT/hypatia.config.yaml" | head -1)"
MODEL="$(sed -n 's/^  design_target_model: //p' "$REPO_ROOT/hypatia.config.yaml" | head -1)"

cat > "$RECIPE" <<EOF
# GENERATED by goose-config/regen-system-prompt.sh — do not edit by hand.
# Edit kernel/*.md (instructions) or this generator, then re-run it.
version: 1.0.0
title: Hypatia
description: Zettelkasten PKB partner for the TabulaJacqueliana vault (Phase 1.5)
instructions: |
$(sed 's/^/  /' "$OUTPUT")

  ---

  ## Substrate note (Goose session — not part of the kernel)

  - Filesystem tools: ALWAYS pass absolute paths. The protocol repo is
    \`$REPO_ROOT\` and the Scholar's vault is \`$VAULT_PATH\`.
  - Work product belongs in the vault; protocol/infrastructure files stay
    in the repo. Do not write elsewhere even if the filesystem permits it.
extensions:
  - type: stdio
    name: hypatia-protocols
    cmd: $REPO_ROOT/target/release/hypatia-protocols-mcp
    args: []
    envs:
      HYPATIA_REPO_ROOT: $REPO_ROOT
    timeout: 300
    description: Hypatia's protocol library + kernel-archive resources (36)
  - type: stdio
    name: filesystem
    cmd: npx
    args:
      - "-y"
      - "@modelcontextprotocol/server-filesystem"
      - "$REPO_ROOT"
      - "$VAULT_PATH"
    timeout: 300
    description: Bounded filesystem access (repo + vault only)
  - type: stdio
    name: time
    cmd: uvx
    args: ["mcp-server-time"]
    timeout: 60
    description: Timestamps for session logging
settings:
  goose_provider: ollama
  goose_model: $MODEL
  temperature: 1.0
EOF

echo "Regenerated $RECIPE (model: $MODEL, vault: $VAULT_PATH)"

# ── Global goosehints (persona for ACP sessions) ───────────────────
# ACP sessions (goose acp / goose serve — e.g. the Obsidian Agent Client
# plugin) can't take a recipe, so the kernel rides the global hints file,
# which Goose loads into every session (~/.config/goose/.goosehints).
# Goose on this machine exists solely for Hypatia, so global is correct;
# revisit if AJ ever uses Goose for non-Hypatia work.
GOOSE_CONFIG_DIR="$HOME/.config/goose"
if [[ -d "$GOOSE_CONFIG_DIR" ]]; then
  {
    echo "<!-- GENERATED from kernel/01-04.md by goose-config/regen-system-prompt.sh -->"
    echo "<!-- Loaded into EVERY goose session on this machine (Hypatia-only). -->"
    echo ""
    cat "$OUTPUT"
    echo ""
    echo "---"
    echo ""
    echo "## Substrate note (not part of the kernel)"
    echo ""
    echo "- Filesystem tools: ALWAYS pass absolute paths. The protocol repo is"
    echo "  \`$REPO_ROOT\` and the Scholar's vault is \`$VAULT_PATH\`."
    echo "- Work product belongs in the vault; protocol/infrastructure files stay"
    echo "  in the repo. Do not write elsewhere even if the filesystem permits it."
  } > "$GOOSE_CONFIG_DIR/.goosehints"
  echo "Regenerated $GOOSE_CONFIG_DIR/.goosehints (kernel persona for ACP sessions)"
fi
