#!/usr/bin/env python3
"""split-decision-routes.py — derive per-route resource files from the
monolithic Decision Routes spec.

The kernel routes most non-trivial work through Route F, but the full
11-decision-routes.md is ~3.4K tokens. Serving each route as its own MCP
resource (`protocol://detail/decision-route-{a..f}`) lets Hypatia load ~1K
tokens of the route she actually picked instead of the whole spec.

The per-route files under docs/reference/phase-1-kernel-archive/decision-routes/
are GENERATED. Never edit them by hand: edit 11-decision-routes.md and re-run
this script. `--check` verifies the generated files match the source (CI gate).

Exit codes:
    0 — files written (or, with --check, all files match)
    1 — --check found stale/missing generated files
    2 — parse error (route sections not found in source)

Invocation:
    python3 scripts/split-decision-routes.py          # regenerate
    python3 scripts/split-decision-routes.py --check  # verify only
"""
from __future__ import annotations

import re
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
SOURCE = REPO_ROOT / "docs/reference/phase-1-kernel-archive/11-decision-routes.md"
OUT_DIR = REPO_ROOT / "docs/reference/phase-1-kernel-archive/decision-routes"

ROUTE_HEADING_RE = re.compile(r"^### Route ([A-F]): (.+?)\s*$")

GENERATED_BANNER = (
    "<!-- GENERATED by scripts/split-decision-routes.py from\n"
    "     docs/reference/phase-1-kernel-archive/11-decision-routes.md.\n"
    "     Do not edit by hand; edit the source and re-run the generator. -->"
)


def extract_routes(source_text: str) -> dict[str, tuple[str, str]]:
    """Return {route letter: (route name, section body)} from the monolith.

    A route section runs from its `### Route X:` heading to the next `### `
    or `## ` heading (whichever comes first), exclusive.
    """
    lines = source_text.splitlines()
    routes: dict[str, tuple[str, str]] = {}
    current: str | None = None
    current_name = ""
    buf: list[str] = []
    for line in lines:
        m = ROUTE_HEADING_RE.match(line)
        if m:
            if current is not None:
                routes[current] = (current_name, "\n".join(buf).strip())
            current = m.group(1)
            current_name = m.group(2)
            buf = [line]
            continue
        if current is not None and re.match(r"^##+ ", line) and not line.startswith("###"):
            routes[current] = (current_name, "\n".join(buf).strip())
            current = None
            buf = []
            continue
        if current is not None:
            buf.append(line)
    if current is not None:
        routes[current] = (current_name, "\n".join(buf).strip())
    return routes


def render(letter: str, name: str, body: str) -> str:
    return (
        f"# Decision Route {letter}: {name} (full spec)\n\n"
        f"{GENERATED_BANNER}\n\n"
        f"Extracted from the Decision Routes spec. The other routes and the "
        f"surrounding Decision Engine phases (intake, KB consultation, "
        f"execution, verification, error recovery) live at "
        f"`protocol://detail/decision-routes`.\n\n"
        f"---\n\n"
        f"{body}\n"
    )


def main() -> int:
    check_only = "--check" in sys.argv[1:]
    if not SOURCE.exists():
        print(f"ERROR: source not found: {SOURCE}", file=sys.stderr)
        return 2
    routes = extract_routes(SOURCE.read_text())
    missing = sorted(set("ABCDEF") - routes.keys())
    if missing:
        print(
            f"ERROR: routes {missing} not found in {SOURCE.name}; "
            "check `### Route X:` headings.",
            file=sys.stderr,
        )
        return 2

    stale: list[str] = []
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    for letter in "ABCDEF":
        name, body = routes[letter]
        out_path = OUT_DIR / f"route-{letter.lower()}.md"
        content = render(letter, name, body)
        if check_only:
            if not out_path.exists() or out_path.read_text() != content:
                stale.append(str(out_path.relative_to(REPO_ROOT)))
            continue
        out_path.write_text(content)
        print(f"wrote {out_path.relative_to(REPO_ROOT)}")

    if check_only:
        if stale:
            print(
                "STALE generated route files (re-run "
                "`python3 scripts/split-decision-routes.py`):"
            )
            for p in stale:
                print(f"  {p}")
            return 1
        print("OK: 6 generated route files match the source.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
